pipeline {
    agent any

    stages {
        stage('Git SCM') {
            steps {
                git 'https://github.com/SurenPonnusamy/TomcatMavenApp'
            }
        }
        stage('Build') {
            steps {
                sh 'cd $WORSKPACE'
                sh 'mvn clean install'
            }
        }
        stage('Packaging') {
            steps {
                sh 'cd $WORKSPACE'
                sh 'mvn package'
            }
        }
        stage('Upload to nexus') {
            steps {
                sh 'curl -v -u admin:admin@123 --upload-file target/TomcatMavenApp-2.0.war http://localhost:8081/repository/java-repo/com.sarav/TomcatMavenApp/2.0/TomcatMavenApp-2.0.war'
            }
        }
        stage('Ansible deployment') {
            steps {
                sh 'cd $WORKSPACE'
                sh 'ansible-playbook ansible-war-deployment/playbook.yml -i ansible-war-deployment/hosts -e target_node=deploy_container'
            }
        }
    }
}

