--- 
- name: Install MongoDB for Debian
  apt:
    name: 
      - mongodb-org={{ major_version }}.{{ minor_version }}
       #- mongodb-org-database-{{ major_version }}.{{ minor_version }}
      - mongodb-org-server={{ major_version }}.{{ minor_version }}
      - mongodb-org-shell={{ major_version }}.{{ minor_version }}
      - mongodb-org-mongos={{ major_version }}.{{ minor_version }}
      - mongodb-org-tools={{ major_version }}.{{ minor_version }}
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install MongoDB for RHEL
  yum:
    name: 
      - mongodb-org-{{ major_version }}.{{ minor_version }}
        #- mongodb-org-database-{{ major_version }}.{{ minor_version }}
      - mongodb-org-server-{{ major_version }}.{{ minor_version }}
      - mongodb-org-shell-{{ major_version }}.{{ minor_version }}
      - mongodb-org-mongos-{{ major_version }}.{{ minor_version }}
      - mongodb-org-tools-{{ major_version }}.{{ minor_version }}  
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"  

- name: Install MongoDB Installer in Windows Server
  win_command: msiexec /i mongodb.msi /qb ADDLOCAL="ServerService,Client"
  args: 
    chdir: C:\\Users
  when: ansible_facts['os_family'] == "Windows"   
